### ISSUE TITLE
Translation possibility and a suggestion of update to the item icon

### ISSUE THREAD

**Issue by ppblitto** [pcal43/copper-hopper#5]
Hello. I'm a Brazilian Portuguese (PT-BR) speaker and it would be awesome if I could do a translation file for the mod. I hope it gets implemented! Right now the copper hoper item as well as the container are named "Item Filter" but I didn't find any en_us.json with the references.

Also, I tweaked the copper hopper texture to be more in line with copper-made items and blocks. I put more shiny spots to give a metalic feel to the item, hope you like it. Feel free to use in the mod.

![copper_hopper](https://user-images.githubusercontent.com/57157437/152607097-106b2dec-9de5-4588-b7a0-bafa7fd82a72.png) ![Bigger](https://user-images.githubusercontent.com/57157437/152607098-004225e8-bf6a-4674-ba0e-a4a06b93a55f.png)

**Comment by pcal43** [comment]
Hi!  Yes, localization support is on my TODO list.  If you wanted give me the pt-be translation, I’ll be sure to include it. 

In the meantime, you can change the name in the copper hopper.json config file if you want.

And thanks so much for the texture!  I’m a terrible artist so that’s really helpful.  Will definitely use it (and give you a shout-out!)

thanks!

**Comment by ppblitto** [comment]
Thanks for the support! I'm happy you like the texture.

**Comment by pcal43** [comment]
Ok, I just released a new version that includes i18n support (with an en_us.json file) and also has your texture.  Thanks again!
